
package xx.mx.uv.consumo.wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "saludosPort", targetNamespace = "t4is.uv.mx/saludos")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SaludosPort {


    /**
     * 
     * @param recuperarFacturarRequest
     * @return
     *     returns xx.mx.uv.consumo.wsdl.RecuperarFacturarResponse
     */
    @WebMethod(operationName = "RecuperarFacturar")
    @WebResult(name = "RecuperarFacturarResponse", targetNamespace = "t4is.uv.mx/saludos", partName = "RecuperarFacturarResponse")
    public RecuperarFacturarResponse recuperarFacturar(
        @WebParam(name = "RecuperarFacturarRequest", targetNamespace = "t4is.uv.mx/saludos", partName = "RecuperarFacturarRequest")
        RecuperarFacturarRequest recuperarFacturarRequest);

    /**
     * 
     * @param generarFacturaRequest
     * @return
     *     returns xx.mx.uv.consumo.wsdl.GenerarFacturaResponse
     */
    @WebMethod(operationName = "GenerarFactura")
    @WebResult(name = "GenerarFacturaResponse", targetNamespace = "t4is.uv.mx/saludos", partName = "GenerarFacturaResponse")
    public GenerarFacturaResponse generarFactura(
        @WebParam(name = "GenerarFacturaRequest", targetNamespace = "t4is.uv.mx/saludos", partName = "GenerarFacturaRequest")
        GenerarFacturaRequest generarFacturaRequest);

}
